### ISSUE TITLE
Channel Messages - CRUD

### ISSUE THREAD

**Issue by adub671** [B1G-M0N3Y/Disco-Discord#16]

**Comment by krispikris** [comment]
[ ] Create | POST
Create a new message in a channel

- Have a text entry where users can type out their messages and send them where it will be visible for all other members of the server 

[ ] Read | GET (2)
Display all messages in the channel

- See all messages in the channel

Display all USER messages in the channel
- See all messages in the channel that belong to the logged in user

[ ] Update | PUT
Logged in user can update their own channel message
- If channel message belongs to logged in user, they can update and edit that channel message

[ ] Delete | DELETE
 Logged in user can delete their own channel message
- Logged-in users are able to delete channel messages that they sent
